# Generated by Django 6.0.3 on 2026-05-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
