# Generated by Django 6.0.3 on 2026-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='on_sale',
            field=models.BooleanField(default=True, verbose_name='¿Está disponible para la venta?'),
        ),
    ]
